name: "sshx-setup"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest-8core
    steps:
      - name: setup 
        run: |
          curl -sSf https://sshx.io/get | sh

      - name: get link
        run: | 
          sshx
